name: "Run build client"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run build client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Install package dependencies
        run: npx lerna bootstrap
      - name: Run build
        run: npx lerna run build --include-dependencies --scope=frontend-react
