name: "PR Close"

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  ENVIRONMENT_NAME: "Development"
  GITHUB_PR_NUMBER: ${{ github.event.number }}

concurrency:
  group: pr-${{ github.event.number }}

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    environment: Development
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Run prepare
        uses: ./.github/actions/prepare
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.DEV_DEPLOY_ROLE }}
          role-session-name: RepoSandboxClientSession
      - name: Run build
        run: pnpm run -r --filter infrastructure... build
      - name: Destroy Infrastructure
        working-directory: apps/my-cool-app/infrastructure
        run: pnpm run cdk destroy --require-approval never
