name: "PR Open"

on:
  pull_request:
    branches:
      - main

env:
  GITHUB_PR_NUMBER: ${{ github.event.number }}
  CI: true

concurrency:
  group: pr-${{ github.event.number }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Nx SHAs
        uses: nrwl/nx-set-shas@v2
      - name: Run prepare
        uses: ./.github/actions/prepare
      - name: Run test
        run: |
          echo "TEST_RESULT_LOG<<EOF" >> $GITHUB_ENV
          pnpm run test >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: test
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test
          message: |
            Unit Test Log
            ```
            ${{ env.TEST_RESULT_LOG }}
            ```
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Nx SHAs
        uses: nrwl/nx-set-shas@v2
      - name: Run prepare
        uses: ./.github/actions/prepare
      - name: Run build
        run: pnpm run build
  deploy:
    needs: [build, test]
    name: Deploy
    runs-on: ubuntu-latest
    environment: Development
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Nx shas
        uses: nrwl/nx-set-shas@v2
      - name: Run prepare
        uses: ./.github/actions/prepare
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.DEV_DEPLOY_ROLE }}
          role-session-name: RepoSandboxClientSession
      - name: Run build
        run: pnpm run build
      - name: Deploy
        run: pnpm run deploy:dev -- -c devSuffix=PR${{ github.event.number }}
